version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@types/vscode"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: "@types/node"
        versions: [">=21.0.0"]
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: maven
    directory: /inject/maven
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: nixpkgs
    commit-message:
      prefix: build
      include: scope
