<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>single</artifactId>
  <version>1.0</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>3.10.3</version>
        <configuration>
          <java>
            <googleJavaFormat>
              <version>1.36.1</version>
            </googleJavaFormat>
          </java>
          <formats>
            <format>
              <includes>
                <include>src/main/java/com/example/twoformats/**/*.java</include>
              </includes>
              <trimTrailingWhitespace/>
            </format>
          </formats>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
